### ISSUE TITLE
Not detect digital persona fingerprint reader

### ISSUE THREAD

**Issue by hertzon** [BrianYeh/UareUSampleJava#1]
Hello, when i try to use UareUSampleJava GET READER button, it shows Reader Not found, plug in a reader and try again, i use android 5, how i can fix this¿????
Best Regards
Nelson

**Comment by BrianYeh** [comment]
You should have the finger printer device. 
Please refer to below company.
http://www.digitalpersona.com/

**Comment by subsub** [comment]
Hi, I have the same problem as hertzon, when I click get reader, it shows Reader Not Found, plug in a reader and try again.
I have the finger printer device `U.Are.U 4500`
Android phones that I use: `Xiaomi Redmi 4A (Android 7.1.2)`, and `Lenovo A7010a48 (Android 5.1)`

Any help would be appreciated.
Thank you
